baseURL: http://smenaaliaga.netlify.app/
languageCode: en-us
title: Titulo Seba's Website

markup:
  goldmark:
    renderer:
      unsafe: true

############################
## ADVANCED
############################

ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$, \.knit\.md$, \.utf8\.md$]